config/routes.rb
Rails.application.routes.draw do
  resources :galleries, only: [:index, :show]
  # resources :images, only: [:index, :show]
  #mount root
  root to: 'index#home'

  mount RailsAdmin::Engine => '/admino4ka', as: 'rails_admin'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get '/contacts', to: redirect('contact')

  get 'index/media/*.*', to: redirect('/media/*.*')

  scope module: :index do
    get :home
    get :faq
    get :blog
    get :shop
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image      :string
#  position   :integer
#

class Gallery < ApplicationRecord
  validates :name, presence: true
  acts_as_list

  mount_uploader :image, ImageUploader

  has_many :images

  # rails_admin do
  #   sort_by :position           # Add Default sorting
  #   sort_reverse false          # sort position increasing ('asc')
  # end

  def create_associated_image(image)
    images.create(fileimage: image)
  end
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  name       :string
#  caption    :string
#  fileimage  :string
#  gallery_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  position   :integer
#

class Image < ActiveRecord::Base
  acts_as_list scope: :gallery_id
  mount_uploader :fileimage, ImageUploader#, :mount_on => :
  belongs_to :gallery
  #validates :name, presence: true
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations


  attr_accessor :name, :email, :content

  validates :name,
            presence: true

  validates :email,
            presence: true

  validates :content,
            presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CarrierWave::DownloadError, :with => :carrierwave_download_error
  rescue_from CarrierWave::IntegrityError, :with => :carrierwave_integrity_error
  before_action :set_section_name

  protected
  def carrierwave_download_error
    flash[:error] = "There was an error trying to download that remote file for upload. Please try again or download to your computer first."
    redirect_to :back
  end

  def carrierwave_integrity_error
    flash[:error] = "There was an error with that remote file for upload. It seems it's not a valid file."
    redirect_to :back
  end
  def set_section_name
       @section = I18n.t("sections.#{controller_path}")
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.order('position ASC')
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    @images = @gallery.images.order('position ASC')
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    #static page
  end

  def faq
    @section = 'faq'
  end

  def blog
    #w.i.p
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      flash[:alert] = "Thank you for your message, in the near future I will try to answer you."
      redirect_to contact_path
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end

  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/galleries/index.html.haml
.container#galerryimagecontainer
 - @galleries.each do |gallery|
  .col-xs-12.col-sm-6.col-md-4.col-lg-3#galerryimage
   - if gallery.image.present?
    = link_to gallery do
     = image_tag gallery.image.thumb.url, class: 'img-thumbnail'
   = link_to gallery.name, gallery, id: "namegallery"

app/views/galleries/show.html.haml
.container
 .gallery-feed
  - @images.each do |image|
   .col-xs-12.col-sm-4.col-md-3.col-lg-3
    - if image.fileimage.present?
     = link_to image.fileimage.url, class: "img", data: { title: CGI::escapeHTML(image.name || "Oups..."), titleOpt: CGI::escapeHTML(image.caption || "Работаем на этим!"), saleOpt: CGI::escapeHTML(image.saleopt || "Уточняйте!"), lightbox: CGI::escapeHTML(@gallery.name) } do
      = image_tag image.fileimage.thumb.url , class: 'img-thumbnail'

app/views/index/_menu.html.haml
%div.container
  %div#navbar
    %ul.nav.navbar-nav
      %li
        = link_to 'home', root_path
      %li
        = link_to 'gallery', [:galleries]
      %li
        %a{:href => "https://www.behance.net/Azyza", :target => "_blank"} blog
      %li
        = link_to 'faq', faq_url
      %li
        = link_to 'contacts', contacts_url
      %li
        %a{:href =>"https://www.etsy.com/shop/Azyza", :target => "_blank"} shop

app/views/index/_profiles_social.html.haml
%div.row
  %p.profiles_social
    %a{:href => 'https://www.instagram.com/azyza_online/', :target => '_blank'}= image_tag 'icons/i.png', class:"img-circle", size: "27x27"
    %a{:href => 'https://www.youtube.com/channel/UCtmKmlSUitnJCiXHPrMHj6Q', :target => '_blank'}= image_tag 'icons/y.png', class:"img-circle", size: "27x27"
    %a{:href => 'https://www.facebook.com/artistAzyza', :target => '_blank'}= image_tag 'icons/f.png', class:"img-circle", size: "27x27"

app/views/index/_section_name.html.haml
%div.section_name=@section

app/views/index/_share_social.html.erb
<div class="container text-center">
  <script type="text/javascript">(function() {
  if (window.pluso)if (typeof window.pluso.start == "function") return;
  if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
  }})();</script>
  <div data-user="127018737" class="pluso" data-background="none;" data-options="medium,square,line,center,horizontal,counter,sepcounter=1,theme=14" data-services="vkontakte,facebook"></div>
</div>

app/views/index/blog.html.erb
<% provide(:title, 'Блог') %>
<h1>Index#blog</h1>
<p>Find me in app/views/index/blog.html.erb</p>

app/views/index/contacts.html.haml
= provide(:title, 'Контакты')

app/views/index/faq.en.html.haml
.container
 .gallery-feed
  .col-xs-12.col-sm-12.col-md-8.col-lg-8#faq
   %blockquote
    %p
     %quest Откуда ты и где живешь?
    %p
     %answer Я родилась и выросла в Тольятти, Самарская область. На данный момент проживаю в Санкт-Петербурге.
   %blockquote
    %p
     %quest Где ты училась? У тебя художественное образование?
    %p
     %answer Я училась в Поволжском Государственном Университете Сервиса. Факультет Дизайна и Прикладного Искусства. Специальность Художник прикладного искусства (резчик по дереву).
   %blockquote
    %p
     %quest Какими материалами ты пользуешь в своих работах?
    %p
     %answer Я работаю в смешенных техниках, поэтому набор творческих инструментов у меня широкий. В основном пишу акрилом любой марки. Для графики использую линеры Sakura, недавно появились спиртовые маркеры Finecolour. В своих работах так же использую сусальное золото, аппликации, бисер, металлическую фурнитуру.
     %answer В линогравюре пользуюсь красками  Charbonnel, резаками Татьянка и линолеумом Горизонт.
   %blockquote
    %p
     %quest Как ты относишься к сотрудничеству с другими иллюстраторами, художниками и творческими людьми?
    %p
     %answer Я рада новым возможностям, которое несут с собой знакомства с креативными людьми. Если у вас есть интересный проект или вы просто хотите обменяться опытом я всегда рада. Пиши мне!
   %blockquote
    %p
     %quest Купить картину, постер, иллюстрацию.
    %p
     %answer Пока что полноценный магазин находиться в разработке, вы можете перейти в мою группу в вКонтакте
     %a{:href => "https:/vk.com/azyza", :target => "_blank"} AZYZA
     %answer и выбрать в разделе товаров все, что вам понравится.
   %blockquote
    %p
     %quest О работе на заказ.
    %p
     %answer Вы можете заказать у меня картину на свободную тему или выбрать из имеющихся у меня готовых графических работ. В целом для понимания, я могу придумать картину с нуля или переработать любой эскиз в живописную работу, в любой цветовой палитре и с учетом Ваших пожеланий. 
     %br
     %answer Для получения полной информации напишите мне письмо на почту, и я вышлю Вам условия работы на заказ.
   %blockquote
    %p
     %quest Мастер классы.
    %p
     %answer Я провожу несколько мастер классов. Линогравюра, декоративная живопись, планета. Подробнее о них Вы можете узнать в моей группе в вконтакте
     %a{:href => "https:/vk.com/azyza", :target => "_blank"} AZYZA.
  .col-xs-12.col-sm-12.col-md-4.col-lg-4
   %div#faq-img
    %img(src="images/foto_me.jpg")
    %p.text-center Меня зовут Олеся.
    %p.text-center Я рисую картины, режу линагравюру, печатаю открытки и постеры. Добро пожаловать на мой сайт.
    %hr
   %img{:src => "images/inst.png", :id => "faq-img-inst"}
    #content-slider
     #slider
      #mask
       %ul
        %li#first.firstanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/1.jpg"}
        %li#second.secondanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/2.jpg"}
        %li#third.thirdanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/3.jpg"}
        %li#fourth.fourthanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/4.jpg"}
        %li#fifth.fifthanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/5.jpg"}
        %li#sixth.sixthanimation
         %a{:href => "https://www.instagram.com/azyza_online/", :target => "_blank"}
          %img{:alt => "", :src => "images/slider/6.jpg"}

app/views/index/home.html.haml
= provide(:title, 'Главная')

.container-fluid
  .main_image
    %img(src="media/main.jpg")

    %br
    %br
    %br
= render "index/share_social"

app/views/layouts/_metrika.html.erb
<!-- Yandex.Metrika counter -->  <!-- /Yandex.Metrika counter -->
<!-- Google Analytics counter -->  <!-- /Google Analytics counter -->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = csrf_meta_tags

    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'



  %body.container-fluid
  = stylesheet_link_tag    'application', media: 'all', 'lightbox': 'reload'
  = javascript_include_tag 'application', 'lightbox': 'reload'

  %div.container-fluid.row.logo_image
    = image_tag 'logo.jpg'
  %div.container-fluid.row
    = render "index/menu"

  %div.container-fliud
    %br
    = render "index/section_name"
    %br
    %br
    = yield
    %hr
    %footer
      = render "index/profiles_social"
      %p
        © 2016
        = succeed "." do
          %a{:href => "https://vk.com/medaved"} Dmitry
        All rights reserved.
        = succeed "." do
          %a{:href => "https://telegram.me/medaved"} Telegram ME
      = render "layouts/metrika"

app/views/messages/new.html.haml
%row.text-center
 .col-lg-12.text-center
  %img#paperairplane(src="media/paperairplane.png")
  %div.container#contacts
   %p= t('.help_text')
  = form_for @message, url: contact_path do |message_form|
   %fieldset
    %div.field#cont_name
     %span.glyphicon.glyphicon-user
     = message_form.text_field :name, class: "input", size: "50x5", placeholder: "Name"
    %div.field#cont_email
     %span.glyphicon.glyphicon-envelope
     = message_form.email_field :email, class: "input", size: "50x5", placeholder: "Email"

     %div.field#cont_text
     = message_form.text_area :content, size: "52x5", class: "input", placeholder: "Message"

    %div.container
     = message_form.submit :button, class: "btn btn-default", value: "Send", size: "7x50"

   - flash.each do |key, value|
    %div{:class => "alert alert-#{key}"}= value

  %hr